### ISSUE TITLE
No language assets

### ISSUE THREAD

**Issue by danjudex** [2amigos/yii2-tinymce-widget#13]
Since version 1.0.0 disappeared assets language why?

**Comment by tonydspaniard** [comment]
@danjudex I am using the tinymce distribution package: https://github.com/2amigos/yii2-tinymce-widget/blob/master/composer.json#L23

Is there a way that we can use the langs with this technique?

**Comment by tonydspaniard** [comment]
@danjudex You are right. Will update the widget with the language files again.
