### ISSUE TITLE
image icon not show in toolbar

### ISSUE THREAD

**Issue by iyoba** [2amigos/yii2-tinymce-widget#15]
Image icon not show in toolbar

**Comment by iyoba** [comment]
Right now it's show, maybe because of cache.

**Comment by tonydspaniard** [comment]
Great... thanks for letting us know

**Comment by pirojok167** [comment]
This is not a cache. I have the same problem. Image icon not show in toolbar.

**Comment by pirojok167** [comment]
I found the problem. 
Need to add "image" in plugins array. 
should get:
'plugins' => [
                "advlist autolink lists link charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste",
                'image',
            ],
