### ISSUE TITLE
Fill textarea onkeyup

### ISSUE THREAD

**Issue by Inttegrum** [2amigos/yii2-tinymce-widget#17]
Is it possible to change de textarea value onkeyup event?

I'm trying to save a text via AJAX but the textarea isn't changing whem I'm editing it.

**Comment by Inttegrum** [comment]
Solved with tinymce.triggerSave(); before trying to save it with AJAX.

**Comment by tonydspaniard** [comment]
@Inttegrum was it with https://github.com/2amigos/yii2-tinymce-widget/blob/master/src/TinyMce.php#L78 ?

**Comment by Inttegrum** [comment]
No.

On my own onClick event I called tinymce.triggerSave(); before getting the data from the form and sending it via AJAX.
