### ISSUE TITLE
Add callback?

### ISSUE THREAD

**Issue by noc2spam** [2amigos/yii2-tinymce-widget#18]
How do I add callbacks? I am trying this:

 	<?php
		$func = "function(editor) {editor.addButton('languages', {text : 'Language', type : 'menubutton', icon : false});}";
		echo $form->field($model, 'content')->widget(TinyMce::className(), [
		'clientOptions' => [
		'plugins' => [
		"advlist autolink lists link charmap print preview anchor",
		"searchreplace visualblocks code fullscreen",
		"insertdatetime media table contextmenu paste"
		],
		'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | languages",
		'setup' => $func
		 
	],
		'options' => ['rows' => 12],
		]);
		?>
Output is  
	`tinymce.init({
		"plugins": ["advlist autolink lists link charmap print preview anchor", "searchreplace visualblocks code fullscreen", "insertdatetime media table contextmenu paste"],
		"toolbar": "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | languages",
		"setup": "function(editor) {editor.addButton('languages', {text : 'Language', type : 'menubutton', icon : false});}",
		"selector": "#pages-content"
	});`
Which should have been:
	`tinymce.init({
		"plugins": ["advlist autolink lists link charmap print preview anchor", "searchreplace visualblocks code fullscreen", "insertdatetime media table contextmenu paste"],
		"toolbar": "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | languages",
		"setup": function(editor) {editor.addButton('languages', {text : 'Language', type : 'menubutton', icon : false});},
		"selector": "#pages-content"
	});`

**Comment by shantinath** [comment]
I am getting an error `TypeError: callback is undefined`

**Comment by noc2spam** [comment]
Okay, I needed `JSExpression`. Closing the issue.
