### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by croatiangrn** [2amigos/yii2-tinymce-widget#19]
How can I add another plugin into yii2-tinymce-widget?

**Comment by pcimagenca** [comment]
'plugins' => [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak", 
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern imagetools"
   ],

Taked from full featured in tinymce web

**Comment by tonydspaniard** [comment]
Thanks @oteroweb
