### ISSUE TITLE
Dealing with with required field.

### ISSUE THREAD

**Issue by PennyScripter** [2amigos/yii2-tinymce-widget#2]
Using the latest Yii2 with your plugin. I have a form rule set with the text field as required. When I try to create a new record and type text in the editor then save I get a message that the text field is empty but I have text in the editor. Can you advise?

**Comment by fruppel** [comment]
Hi, are there any news about this issue?

**Comment by akorinek** [comment]
Please fix this issue, as it makes the widget not usable in production
