### ISSUE TITLE
file_picker_callback / file_browser_callback

### ISSUE THREAD

**Issue by ahalejcio** [2amigos/yii2-tinymce-widget#20]
Hi,
I found problem with assign tinymce to file browser (function)
sample code:
```php 
<script>function nameJsFunction().....</script>
 
 <?= $form->field($model, 'content')->widget(TinyMce::className(), [
         'options' => ['rows' => 16],
         'language' => 'en_GB',
         'clientOptions' => 
             'file_picker_callback' => 'nameJsFunction',
         ]
     ]); ?>
```
this generate something like this:
"file_picker_callback":**"**nameJsFunction**"** but nameJsFunction, can't be in quotations.

Sample solution, maybe is something better, but that works for me:

TinyMce.php
after $options

> // @codeCoverageIgnoreEnd
>        $options = Json::encode($this->clientOptions);
> 
> ```
>   //check is there editor and replace "function" to function 
>     if(isset($this->clientOptions['file_picker_callback']))
>         $options = str_replace('"'.$this->clientOptions['file_picker_callback'].'"', $this->clientOptions['file_picker_callback'], $options);
> ```

i guess something like this is should be for "file_browser_callback" too,

> if(isset($this->clientOptions['file_browser_callback']))
>             $options = str_replace('"'.$this->clientOptions['file_browser_callback'].'"', $this->clientOptions['file_picker_callback'], $options);

**Comment by tonydspaniard** [comment]
@ahalejcio to do that, please use `new JsExpression('nameJsFunction')`

**Comment by ermGit** [comment]
This should be in the documentation for the Widget.  It would save people a lot of time.

**Comment by tonydspaniard** [comment]
Thanks @ermGit
