### ISSUE TITLE
apply custom skin

### ISSUE THREAD

**Issue by philbluefox** [2amigos/yii2-tinymce-widget#21]
How can I apply my custom skin? How can I add it to assets?

**Comment by insane-dev** [comment]
Hi, maybe it is too late, but nevertheless...

To change editor skin you need to specify where the new skin is stored, e.g.:

```php

$form->field($model, 'content')->widget(TinyMce::className(), [
    'clientOptions' => [
        // ...
        'theme' => 'modern',
        'skin' => 'light',
        // this will look for skin e.g. in 
        // `yii2-app-advanced/backend/web/css/tinymce/skins/light` dir
        'skin_url' => '/css/tinymce/skins/light', 
        // ...
    ],
]);

```

See TinyMCE docs about [skin_url](https://www.tinymce.com/docs/configure/editor-appearance/#skin_url).

**Comment by tonydspaniard** [comment]
thanks @insane-dev
