### ISSUE TITLE
language files

### ISSUE THREAD

**Issue by ComradePashka** [2amigos/yii2-tinymce-widget#22]
if you set up language to 'en' there is no en.js file at langs folder of corresponding asset but only en_CA.js and en_GB.js, so if I try to use ISO-639 two-letters language variable at multilanguage site I will get error everytime I switch to English.

**Comment by mmalisz** [comment]
Bumping this issue.

**Comment by tonydspaniard** [comment]
what you propose @mmalisz ?

**Comment by mmalisz** [comment]
@tonydspaniard, well, I use two languages for my app: polish (pl-PL) and english (en-UK). As for polish, simple explode works, however, as stated in original report, en doesn't work. Given that, I had to make special case for 'en' -- detecting UK in Yii::$app->languages then producing proper language string.
Haven't looked at the code of the widget, but I see that 'language' param is not defined within 'clientOptions', so maybe some switch-case on the widget side will be enough.

**Comment by tonydspaniard** [comment]
This has been fixed on latest update
