### ISSUE TITLE
Facing issue during image upload on server

### ISSUE THREAD

**Issue by mohdbashir** [2amigos/yii2-tinymce-widget#23]
It is working on localhost.  
but when uploaded on server and click of upload icon it showing the upload dialog with error: -

NetworkError: 404 Not Found - http://mydomain.com/admin/assets/5802b69e/plugins/jbimages/ci/index.php?blank"

Once click on browse icon it also showing error: 
"NetworkError: 404 Not Found - http://mydomain.com/admin/assets/5802b69e/plugins/jbimages/ci/index.php?upload/english"

![upload-an-image-](https://cloud.githubusercontent.com/assets/3686692/11837093/cc17d4c6-a404-11e5-89a6-7498ee635562.png)

**Comment by mohdbashir** [comment]
please help to fixing the above issue.

**Comment by tonydspaniard** [comment]
really sorry for the
