### ISSUE TITLE
Facing issue when the plugin is used in Modal

### ISSUE THREAD

**Issue by malaynayak** [2amigos/yii2-tinymce-widget#24]
I am using this plugin in a form and the fom is loaded in a modal dialog. If the modal is loaded for the first time the plaugin works fine. The problem occures when the modal is opened more than once. The plugin does not get initialised perhaps.
![capture1](https://cloud.githubusercontent.com/assets/8335661/12552252/a0d31968-c396-11e5-961d-55baf1cebc0e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8335661/12552254/a5c96c88-c396-11e5-80fb-6834e6b8cec8.PNG)

**Comment by tonydspaniard** [comment]
@malaynayak The problem with modals is that they clone the content of a layer. Therefore you need to call the initialization of the widget each time the popup opens. I highly recommend you to make use of the asset class only and then add the initialization js script on your on before show modal function.
