### ISSUE TITLE
Problem while using bootstrap

### ISSUE THREAD

**Issue by it3rmit** [2amigos/yii2-tinymce-widget#4]
I use bootstrap in my yii2 application. When I use yii2-tinymce widget I get the the modal window with breaked styles (shown on the picture). After searching the solution, I found that bootstrap styles rewrite tynimce styles. 
![incorrect image](http://www.imageup.ru/img258/1904616/incorrect.jpg)
When I clear bootstrap.css file in assets, tinymce works perfect (shown on the picture).
![correct image](http://www.imageup.ru/img258/1904619/proper.jpg)
What are the solutions to solve this problem? Thanks.

**Comment by tonydspaniard** [comment]
bump
