### ISSUE TITLE
No Javascript imports

### ISSUE THREAD

**Issue by zibra** [2amigos/yii2-tinymce-widget#6]
Hi,

I can't get extension work. It was correctly installed via composer, no php error appear but also no javascript imports are added to my template and my form look like this (content field):
![Form](http://centralpixel.pl/form.JPG)
What is wrong?

**Comment by tonydspaniard** [comment]
@zibra it all looks fine to me.

**Comment by tonydspaniard** [comment]
bump

**Comment by PaulVanSchayck** [comment]
Hmm.. I can possibly confirm this bug. Using latest 1.0 version.

In TinyMceAsset.php the $sourcePath is set to `'@vendor/tinymce'`. For me (using composer), tinymce is placed in `@vendor/tinymce/tinymce`.

**Comment by tonydspaniard** [comment]
You are right. Its fixed now (check master and let me know). Sorry was speed coding.

**Comment by tonydspaniard** [comment]
@PaulVanSchayck updated the version tag to "v1.0.1" should be ok now

**Comment by PaulVanSchayck** [comment]
Thanks, works fine now!

**Comment by tonydspaniard** [comment]
@PaulVanSchayck happy to know
