### ISSUE TITLE
Not saving data in single click

### ISSUE THREAD

**Issue by Logixwebtech** [2amigos/yii2-tinymce-widget#7]
Hi ,
Greetings!

I am using this editor in my web app. When i click submit button first time to submit form, text editor field says 'Description can not be blank'. Even it has already filled value. When i click submit button. It save the value.

In short, Text editor shows error for first submission.
Please help me.

Thanks
Hari

**Comment by tonydspaniard** [comment]
@Logixwebtech I need to make a fix like I did on CKEditor: https://github.com/2amigos/yii2-ckeditor-widget/blob/master/assets/js/dosamigos-ckeditor.widget.js#L14

**Comment by Logixwebtech** [comment]
Hi Tony,

Thanks for quick response.
When your fixed changes will be available to use? 
For that change i need to run composer update or need to do anything else?

Please help me. 

Thanks
Hari

**Comment by tonydspaniard** [comment]
This should be fixed with version "1.0.0"

**Comment by ipppinto** [comment]
Hi,

I have the version 1.0.3 and I have the same problem.

Thank you.

**Comment by tonydspaniard** [comment]
@ipppinto We should add the 'onchange' event to fill the textarea. Reopened this issue to fix it.

**Comment by tonydspaniard** [comment]
@ipppinto Mind checking if you have this script inserted in your webpage? https://github.com/2amigos/yii2-tinymce-widget/blob/master/src/TinyMce.php#L78

**Comment by ipppinto** [comment]
Hi,

My rules:
    public function rules()
    {
        return [
            [['user_id', 'assunto', 'descricao'], 'required'],
            [['user_id'], 'integer'],
            [['data_registo'], 'safe'],
            [['text'], 'string'], <- this is text area
            [['assunto', 'descricao', 'link'], 'string', 'max' => 255],
            [['link'], 'url'],
        ];
    }

To render I use this:

<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\tinymce\TinyMce;
/* @var $this yii\web\View */
/* @var $model common\models\Noticia */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="noticia-form">
    <div class="row">
        <?= Html::errorSummary($model, ['class' => 'errors']) ?>
        <div class="col-lg-6">   
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'assunto')->textInput(['maxlength' => 255]) ?>

            <?= $form->field($model, 'descricao')->textInput(['maxlength' => 255]) ?>

            <?= $form->field($model, 'link')->textInput(['maxlength' => 255])->hint('Link completo: http://...') ?>
            
            <?= $form->field($model, 'text')->widget(TinyMce::className(), [
                'options' => ['rows' => 6],
                'language' => 'es',
                'clientOptions' => [
                    'plugins' => [
                        "advlist autolink lists link charmap print preview anchor",
                        "searchreplace visualblocks code fullscreen",
                        "insertdatetime media table contextmenu paste"
                    ],
                    'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                ]
            ]);?>
            
            <?= $form->field($model, 'notificacao')->dropDownList(['0'=>'Não enviar email de notificação', '1'=>'Enviar email de notificação aos utilizadores registados'], ['prompt'=>'Escolha a opção']); ?>            
                        
            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? 'Criar' : 'Atualizar', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

**Comment by tonydspaniard** [comment]
@ipppinto mind showing the final rendered javascript too? Thanks!

**Comment by lexeo** [comment]
Hello. Thank you for this widget.

I'm using v1.0.3 and unfortunatelly I have the same issue. Widget renders as expected with all JS code, validation is passing only at the second attempt.
I've tried to call console.log(e) inside "change" event handler, but variable "e" has no such property as "content". That is why your solution doesn't work for me.
Also I think that $.off('change') is not the best idea. Because we may need to set custom "change" event handler.
I've tried to replace one line of code with: https://github.com/maybeworks/yii2-tinymce/blob/master/TinyMceWidget.php#L109
and it really works. 
What do you think?

**Comment by tonydspaniard** [comment]
@lexeo Thank you so much for your hint. To tell you the truth I didn't even thought that yii may override methods such as: https://github.com/2amigos/yii2-tinymce-widget/blob/master/src/TinyMce.php#L78

I will make the change asap!. 

Thanks again

**Comment by tonydspaniard** [comment]
@lexeo @Logixwebtech @ipppinto mind testing version 1.1.0? Should be fixed thanks to @lexeo
